# Generated by Django 4.1.4 on 2022-12-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_postlike_post_unlike_alter_postlike_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='like',
            field=models.CharField(choices=[('+', 'Like'), ('-', 'Unlike')], max_length=1, null=True),
        ),
    ]
