# Generated by Django 4.1.4 on 2022-12-21 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_postlike_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('user', 'post_like')},
        ),
    ]
